services:
  simple-apps:
    container_name: ct-simpleapps-prod
    build: ./app
    image: rizky12mui/img-simpleapps:v1-stable
    ports:
      - "10001:3000"
    restart: always
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 128M
